### ISSUE TITLE
Ratio-based recipes

### ISSUE THREAD

**Issue by ChishaWolf** [rozPierog/Cofi#100]
**Is your feature request related to a problem? Please describe.**

Currently it seems impossible to multiply brew amount (e.g. when I want to brew 15g beans with 250ml water using the default James Hoffmann's V60) without editing the whole recipe. 

**Describe the solution you'd like**

Adding a feature that allows multiplying coffee amount would be great!

**Describe alternatives you've considered**

**Additional context**

As a reference, here's a screenshot of the feature that I'm requesting on another brew timer app.
![Screenshot_20221006_140921_Brew Timer](https://user-images.githubusercontent.com/78742042/194227239-5162f006-55e0-4964-9411-58a4c2c1e292.jpg)
Apologies for possible errors in my text, since English is not my native language.

**Comment by rozPierog** [comment]
Hey @ChishaWolf I'm starting designing this feature, can you give some insight what you would like to see here?
I'm thinking of: 

- Adding `multiplier` picker that would have input for any number that user wants, and `multiply time needed for steps`
- Water and Coffee values would be multiplied by value provided by user
- Time needed for steps would only be multiplied if user selected that option

Does that sound like something that you would use? What are you looking for in this feature?

**Comment by forestwalker93** [comment]
@rozPierog hi! Just found your app, and came here to say thank you and salute for Hoffman's recepies and for exact same request of Ratio brewing :)
I used this awesome site for fast calculations (it also have various recepies on page)
https://www.felipecorvalan.cl/coffeecalc/

You may find it useful for designing :)

Speaking of time multiplier - good shot , and good idea about picker -  time for pouring over increased  amount of water is sometimes a nonlinear change due to pouring techniques, so  basic logic of multiplied time may feel more confusing than useful for someone.

**Comment by rozPierog** [comment]
Thanks @forestwalker93 this will be a great help. Yes I'm aware that just simply multiplying all values will not get you a great result, that's why I will seek counsel of my fellow coffee geeks in a coming weeks to find some answers

**Comment by ChishaWolf** [comment]
@rozPierog Hey, sorry for the late reply (something off with my mail app). This solution sounds great to me! 👍  Although I don't quite get why time need to be multiplied, since it's unusual to multiply the duration of the recipe as a whole. That being said, it may be useful to someone else, and an extra function wouldn't hurt! :) Thanks for your time and effort, really love this app!

**Comment by rozPierog** [comment]
@ChishaWolf Time need to change to ensure proper extraction for different coffee amount, if you have to rush to pour lots of water because the timer is rushing you, you will agitate the coffee bed. It's not _that_ significant (but still will result in different brews) when you are lowering the dose, but I want a solution that will work for both cases.

Thank you for your support and kind words!

**Comment by jswetzen** [comment]
I came here to suggest this feature as well, and your attention to detail even to the timing @rozPierog is wonderful. Coffee, UI and UX excellence: I love it!

**Comment by rozPierog** [comment]
Good news everyone,

After bashing my head against the wall trying to figure out best way to do this for the last weeks, it struck me. I should go back to the roots of Cofi, and just make it open for whatever user wants to do. 
So I present to you: #112 
If all goes well I'll ship the update today
