### ISSUE TITLE
Wear OS Companion app

### ISSUE THREAD

**Issue by AmaryllisVFX** [rozPierog/Cofi#108]
**Is your feature request related to a problem? Please describe.**

Currently it is not possible to use Cofi without having your phone near you or be able to control the timer from the PiP window.

**Describe the solution you'd like**

It would be great to have a Wear OS companion app if possible for Cofi (preferably one that supports Wear OS 2) to access your recipes, run them and be able to control the timer all from the watch. 

**Describe alternatives you've considered**

Having a notification be created while running a recipe with action buttons so it could be controlled from the watch without needing to create a separate Wear OS companion app. This would of course offer limited functionality compared to having a dedicated Wear OS app but would still be an improvement over the current implementation.

**Comment by rozPierog** [comment]
Ah yes, I thought about creating some kind of Standalone/Companion app for wearOS ever since Galaxy Watch with wear OS came out. Tho I'm afraid that I wouldn't do it justice, as I don't have a wearOS device (sans 1st gen Moto 360 but that's just ancient at this point 😅)

I'll look into wearOS documentation at some point to see what I can do there. In a meantime as a wearOS user could you @AmaryllisVFX give me some context as to what would expect from wearable Cofi?
What information to display, how to sync between phone and a watch (or should it be completely separate?), should there be an option to "continue on phone/watch" that would open the app on a second device, etc.
As I said I have no idea how watch apps work these days so any and all feedback would be welcome

**Comment by AmaryllisVFX** [comment]
In my opinion, having the Wear OS app be a companion rather than a standalone app would be a much better experience. Since creating recipes and editing them on the watch would be difficult and there would have to be a compromise either with functionality or design to fit everything on the smaller display.

The companion app would display the currently running recipe name, the timer, the step name (add coffee, add water etc.) and have the play/pause button similar to the phone app (potentially also controlled using hardware buttons on the watch).

> should there be an option to "continue on phone/watch" that would open the app on a second device, etc.

Yes, either a button in the phone app to open the watch app or have the watch app open automatically once a recipe is started.

I'd be happy to help with any further feedback you require!

**Comment by rozPierog** [comment]
I've made some progress on a wearOS app, but it's still a long way out! It's harder than I expected as it's basically a whole new app with only parts of the codebase shared between.
Can you @AmaryllisVFX how would you see hardware button control working? Let's call Button 1 a button above crown, and Button 2 clickable crown.

https://user-images.githubusercontent.com/23499434/197336343-855bd599-a7a0-49ee-98b9-c8c2f4a48470.mov

**Comment by AmaryllisVFX** [comment]
This looks promising so far! I'd say button 1 could be used as the play/pause button. The primary button (which is the clickable crown in some watches like Fossils) serves as the home button so you couldn't set a different function to it. However, Fossil watches(and maybe some others like it) have a 3rd button below the crown which could be used for another function. I can't think of anything it could be used for though.
