### ISSUE TITLE
Send recipes from phone to the wear os app

### ISSUE THREAD

**Issue by civ2boss** [rozPierog/Cofi#121]
**Is your feature request related to a problem? Please describe.**

I was trying to add recipes I created on the phone app to sync to the wear os app, but I don't see a way to do so.

**Describe the solution you'd like**

I would like a sync button that will send recipes or maybe a selection of recipes I created on the phone app to the wear os app.

**Describe alternatives you've considered**

No alternative I can think of right now since I think the wear os app is pretty feature light.

**Additional context**

**Comment by rozPierog** [comment]
WearOS app should have received recipes as soon as you've made changes on your phone.
I don't have any physical WearOS watches to test it though, but it worked on an emulator.
Could you try doing this:
- open the wearOS app
- open the Android app
- edit one of the recipes (change name, maybe step)
- observe if changes propogated to the watch

It would be also helpful if you could provide information about your watch, and which version of the Cofi app are you using @civ2boss 

Also as you pointed out, yes Cofi on a watch is pretty simple, because I could figure out what else could be needed there. If you have any ideas that would make it better for you I'll be happy to hear them!

**Comment by civ2boss** [comment]
So I have a Google Pixel Watch which doesn't let me install it through the Play Store so I sideloaded the app from the apk on github. The phone app I did install through Play Store though, so I wonder if that's the issue.

**Comment by civ2boss** [comment]
Ok update I uninstalled the sideloaded version, then I clicked the prompt in the phone app to install on the phone which did allow me to install to the watch. Then after I edited and saved the recipe again, it finally showed up on the watch!

**Comment by rozPierog** [comment]
I'm glad it worked!
