### ISSUE TITLE
Tea support?

### ISSUE THREAD

**Issue by SeriousBug** [rozPierog/Cofi#203]
**Is your feature request related to a problem? Please describe.**

The title is a bit joking, but I'm also using Cofi as a timer when I'm brewing tea. It would be nice to add a few little touches to better support this use case.

**Describe the solution you'd like**

Adding a few tea icons to use in recipes would be enough. A further improvement would be to add a "Add Tea" button, but the "Other" option is enough for that.

**Describe alternatives you've considered**

Adding the ability to put custom icons for recipes would also work.

Otherwise right now I just pick an existing icon that I'm not already using for coffee recipes.

**Additional context**

**Comment by rozPierog** [comment]
Using Cofi for tea? Blasphemy! I guess I need to make another app called `Ti` or `Chai` 😅 
I just hope that my work on #201 will make Cofi better for tea as well, as it is a much less involved process!

I would be happy to add some tea icons. 
As it was a case with #130 and #146, I would like to keep them consistent, and hire my [friendly neighborhood designer](https://creativby.com/hubert/) to draw them. 
To hire him, I'll need to pay him fairly, so just like in the previous issues about icons I'll humbly ask for a donation of at least 10€ so that I can cover that cost, and you can name two icons that you would like to see there.

**Comment by SeriousBug** [comment]
Very reasonable! I just sent a $20 donation.

Icon-wise I'd love to see:
- A tea cup or mug with a tea bag
- A teapot

It's fine if you or the designer come up with something else though. I'll leave the design up to your amazing designer!

**Comment by rozPierog** [comment]
Thank you! You can except new icons in the next (or one after that) release.
